### ISSUE TITLE
compile error 

### ISSUE THREAD

**Issue by bill790** [js2xxx/oceanic#11]
Finished dev [unoptimized + debuginfo] target(s) in 0.21s
/usr/lib/llvm-14/bin/llvm-objcopy: error: 'debug/BootX64.efi.sym': debug directory not found
Building VDSO
   Compiling proc-macro2 v1.0.51
   Compiling unicode-ident v1.0.6
   Compiling quote v1.0.23
   Compiling serde_derive v1.0.152
   Compiling autocfg v1.1.0
   Compiling indexmap v1.9.2
   Compiling syn v1.0.107
   Compiling serde_json v1.0.93
   Compiling heck v0.4.1
   Compiling sv-gen v0.1.0 (/home/xiechen/workspace/oceanic/h2o/libs/syscall_gen)
   Compiling serde v1.0.152
   Compiling toml v0.5.11
   Compiling cbindgen v0.24.3
   Compiling sv-call v0.1.0 (/home/xiechen/workspace/oceanic/h2o/libs/syscall)
error: linker `lld` not found
  |
  = note: No such file or directory (os error 2)

error: could not compile `sv-call` due to previous error
Error: failed to build VDSO

Caused by:
    0: cargo returned error
    1: process exited unsuccessfully: exit status: 101

**Comment by js2xxx** [comment]
Please install lld to solve the problem, because I set the default linker of rust to be it. I'll add it in the dependency list in readme.
