### ISSUE TITLE
cargo xtask dist img 报错

### ISSUE THREAD

**Issue by Warser0898** [js2xxx/oceanic#5]
按照readme里的步骤编译，到 cargo xtask dist img这一步报错：

error: failed to build h2o_boot

caused by:
    no such file or directory (os error 2)

**Comment by Golden-Pigeon** [comment]
同样的错误

**Comment by mingshuisheng** [comment]
会不会是缺少lld，试试apt install lld，之后再执行

**Comment by Warser0898** [comment]
> 会不会是缺少lld，试试apt install lld，之后再执行

试过了，不行

**Comment by js2xxx** [comment]
llvm 14安装还有环境变量配置了吗

EDIT: 更新了下生成工具的报错显示，如果继续出错请发个新的报错信息。

**Comment by Golden-Pigeon** [comment]
解决了，是LLVM_PATH环境变量的问题。

抱歉，是没有认真看构建流程
